version: '3'
services:

  web:
    container_name: doc
    hostname: doc
    build: ./doc
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    working_dir: ${CONTAINER}
    volumes:
      - ${LOCAL}:${CONTAINER}
      - ./doc/vhost.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_RUN_GROUP=#1000
      - APACHE_RUN_USER=#1000

  composer:
    image: composer:1.10
    volumes:
      - ${LOCAL}:${CONTAINER}
    working_dir: ${CONTAINER}
    command: composer install