version: '3'
services:

  web:
    container_name: web
    hostname: web
    build: ./web
    restart: always
    ports:
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    environment:
      - APACHE_RUN_USER=#1000

  composer:
    image: composer:1.10
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install